# Generated by Django 5.0.6 on 2024-05-27 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Apply', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='document',
        ),
    ]
