# Generated by Django 5.0.6 on 2024-05-27 15:37

import Apply.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apply', '0003_rename_application_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(default=1, upload_to=Apply.models.profile_pic),
            preserve_default=False,
        ),
    ]
