# Generated by Django 5.0.6 on 2024-05-29 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apply', '0007_application_address_application_city_and_more'),
        ('Courses', '0002_alter_course_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Courses.course'),
            preserve_default=False,
        ),
    ]
