# Generated by Django 5.0.6 on 2024-05-19 14:47

import Accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(upload_to=Accounts.models.profile_image),
        ),
    ]
