# Generated by Django 5.0.3 on 2024-04-04 15:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0002_coupon'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Variation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_value', models.CharField(max_length=150)),
                ('size_value', models.CharField(max_length=150)),
            ],
        ),
        migrations.AddField(
            model_name='cart_item',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cart_item',
            name='variations',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Cart.variation'),
            preserve_default=False,
        ),
    ]
