# Generated by Django 5.0.3 on 2024-04-04 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0003_variation_cart_item_user_cart_item_variations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart_item',
            name='cart',
        ),
    ]
