# Generated by Django 5.0.3 on 2024-04-04 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0004_remove_cart_item_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart_item',
            name='variations',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Cart.variation'),
        ),
    ]
