# Generated by Django 5.0.3 on 2024-04-07 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0005_alter_cart_item_variations'),
        ('Store', '0004_delete_variation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='variation',
            options={'verbose_name': 'Variation', 'verbose_name_plural': 'Variations'},
        ),
        migrations.AddField(
            model_name='variation',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='variation',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Store.product'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='variation',
            name='color_value',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='variation',
            name='size_value',
            field=models.CharField(max_length=50),
        ),
    ]
