# Generated by Django 5.0.3 on 2024-04-08 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0007_order_orderproduct'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='Email',
            new_name='email',
        ),
    ]
