# Generated by Django 5.0.3 on 2024-04-11 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0008_rename_email_order_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coupon',
            options={'verbose_name': 'coupon', 'verbose_name_plural': 'coupons'},
        ),
    ]
