# Generated by Django 5.0.3 on 2024-04-16 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0010_order_coupon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='discount',
            new_name='percent',
        ),
    ]
