# Generated by Django 5.0.3 on 2024-04-16 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0011_rename_discount_coupon_percent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='coupon',
        ),
        migrations.AddField(
            model_name='coupon',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
