# Generated by Django 5.0.3 on 2024-04-16 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0012_remove_order_coupon_coupon_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
