# Generated by Django 5.0.3 on 2024-04-16 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0013_alter_coupon_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='coupon',
            field=models.ManyToManyField(blank=True, to='Cart.coupon'),
        ),
    ]
