# Generated by Django 5.0.3 on 2024-04-16 03:59

import shortuuid.django_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0014_order_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='oid',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', blank=True, length=5, max_length=20, null=True, prefix=''),
        ),
    ]
