# Generated by Django 5.0.3 on 2024-04-16 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0015_order_oid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='oid',
        ),
    ]
