# Generated by Django 5.0.3 on 2024-04-17 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0016_remove_order_oid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='coupon',
        ),
    ]
