# Generated by Django 5.0.3 on 2024-04-17 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0018_order_coupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='coupon',
            field=models.CharField(max_length=50),
        ),
    ]
