# Generated by Django 5.0.3 on 2024-04-07 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0003_variation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Variation',
        ),
    ]
