# Generated by Django 5.0.3 on 2024-04-18 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0005_product_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='offerprice',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
