# Generated by Django 5.0.3 on 2024-04-19 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0007_alter_product_offerprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='offerpercent',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
