# Generated by Django 5.0.3 on 2024-05-01 04:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0009_alter_offer_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Store.product'),
        ),
    ]
