# Generated by Django 5.0.3 on 2024-05-20 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0011_alter_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
