# Generated by Django 5.0.3 on 2024-05-20 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0012_product_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
    ]
