# Generated by Django 5.0.6 on 2024-06-01 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='offer_percent',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tour',
            name='offer_price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
