# Generated by Django 5.0.6 on 2024-06-01 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0002_tour_offer_percent_tour_offer_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='offer_percent',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tour',
            name='offer_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
