# Generated by Django 5.0.6 on 2024-05-26 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('Hours_1', models.CharField(max_length=50)),
                ('Hours_2', models.CharField(max_length=50)),
                ('location_1', models.CharField(max_length=50)),
                ('location_2', models.CharField(max_length=50)),
                ('book_1', models.CharField(max_length=50)),
                ('book_2', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Meeting',
                'verbose_name_plural': 'Meetings',
            },
        ),
    ]
