# Generated by Django 5.0.6 on 2024-05-26 16:22

import Meetings.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Meetings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='image',
            field=models.ImageField(default=1, upload_to=Meetings.models.meeting_image),
            preserve_default=False,
        ),
    ]
