# Generated by Django 5.0.6 on 2024-05-23 15:09

import Courses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0004_alter_course_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=Courses.models.course_image),
        ),
    ]
