# Generated by Django 5.0.6 on 2024-05-21 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0003_cart_item_variations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart_item',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
