# Generated by Django 5.0.6 on 2024-05-21 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0004_alter_cart_item_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart_item',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
