# Generated by Django 5.0.6 on 2024-05-21 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0005_alter_cart_item_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart_item',
            name='quantity',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
