# Generated by Django 5.0.6 on 2024-05-22 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0007_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart_item',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Cart.coupon'),
        ),
    ]
