# Generated by Django 5.0.6 on 2024-06-04 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0002_alter_booking_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='tour',
            field=models.CharField(max_length=50),
        ),
    ]
