# Generated by Django 5.0.6 on 2024-05-15 15:39

import Store.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50)),
                ('category_slug', models.SlugField(blank=True, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Sub_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_name', models.CharField(max_length=50)),
                ('sub_slug', models.SlugField(blank=True, null=True, unique=True)),
                ('sub_image', models.ImageField(upload_to=Store.models.subimage)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Store.category')),
            ],
            options={
                'verbose_name': 'Sub_Category',
                'verbose_name_plural': 'Sub_Categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_name', models.CharField(max_length=50)),
                ('pro_slug', models.SlugField(blank=True, null=True, unique=True)),
                ('pro_stock', models.IntegerField()),
                ('pro_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pro_description', models.TextField()),
                ('pro_image', models.ImageField(upload_to=Store.models.proimage)),
                ('pro_offer_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pro_offer_percent', models.IntegerField()),
                ('sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Store.sub_category')),
            ],
        ),
    ]
