# Generated by Django 5.0.6 on 2024-05-17 10:46

import Store.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0003_alter_product_pro_offer_percent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=Store.models.catimage),
            preserve_default=False,
        ),
    ]
