# Generated by Django 5.0.6 on 2024-05-21 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0005_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pro_offer_price',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='pro_price',
            field=models.FloatField(),
        ),
    ]
