# Generated by Django 5.0.6 on 2024-05-25 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0002_appointment_created_at_appointment_is_available'),
        ('Courses', '0006_alter_course_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='car_type',
            field=models.CharField(choices=[('Manual', 'Manual'), ('Automatic', 'Automatic')], max_length=50),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='courses',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Courses.course'),
        ),
    ]
