# Generated by Django 5.0.6 on 2024-05-25 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0003_alter_appointment_car_type_alter_appointment_courses'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_type', models.CharField(choices=[('Manual', 'Manual'), ('Automatic', 'Automatic')], max_length=50)),
            ],
            options={
                'verbose_name': 'car_type',
                'verbose_name_plural': 'car_type',
            },
        ),
        migrations.AlterField(
            model_name='appointment',
            name='car_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Appointment.car_type'),
        ),
    ]
