# Generated by Django 5.0.6 on 2024-05-25 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0004_car_type_alter_appointment_car_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car_type',
            name='car_type',
            field=models.CharField(max_length=50),
        ),
    ]
