# Generated by Django 5.0.6 on 2024-05-25 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0005_alter_car_type_car_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='car_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='courses',
            field=models.CharField(max_length=50),
        ),
    ]
