# Generated by Django 5.0.6 on 2024-05-25 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0008_alter_car_type_car_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'verbose_name': 'Appointment', 'verbose_name_plural': 'Appointments'},
        ),
    ]
