# Generated by Django 5.0.6 on 2024-05-25 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0009_alter_appointment_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car_type',
            options={'verbose_name': 'car_type', 'verbose_name_plural': 'car_types'},
        ),
    ]
