# Generated by Django 5.0.6 on 2024-05-25 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0010_alter_car_type_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
